services:
  - type: web
    name: crash-app
    runtime: node
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: node server/src/index.js
    plan: free
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.13.0
      - key: PORT
        value: 10000
